# Generated by Django 4.0 on 2021-12-23 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description_1', models.CharField(max_length=255, verbose_name='something1')),
                ('description_2', models.IntegerField(verbose_name='something2')),
                ('description_3', models.CharField(max_length=255, verbose_name='something3')),
                ('description_4', models.IntegerField(verbose_name='something4')),
                ('description_5', models.CharField(choices=[('ph1', 'PH1'), ('ph2', 'PH2'), ('ph3', 'PH3'), ('pz', 'PZ')], max_length=255, verbose_name='something5')),
                ('description_6', models.IntegerField(verbose_name='something6')),
                ('description_7', models.CharField(max_length=255, verbose_name='something7')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screw.categories', verbose_name='Категория товара')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description_1', models.CharField(max_length=255, verbose_name='something1')),
                ('description_2', models.IntegerField(verbose_name='something2')),
                ('description_3', models.CharField(max_length=255, verbose_name='something3')),
                ('description_4', models.IntegerField(verbose_name='something4')),
                ('description_5', models.CharField(max_length=255, verbose_name='something5')),
                ('description_6', models.IntegerField(verbose_name='something6')),
                ('description_7', models.CharField(max_length=255, verbose_name='something7')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screw.product', verbose_name='Продукт к которому относитья товар')),
            ],
        ),
    ]
