# Generated by Django 4.0 on 2021-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Категория для товара'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Основной продукт'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Продукты относящиеся с товару'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
