# Generated by Django 4.0 on 2021-12-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screw', '0002_alter_categories_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
